### ISSUE TITLE
`Error` doesn't implement `std::error::Error`

### ISSUE THREAD

**Issue by d3zd3z** [softprops/goji#11]
The `Error` type does not implement `std::error::Error` and therefore cannot be easily used with '?' (or try!()). I would recommend building the Error type with the `error_chain!()` macro, as it avoid the boilerplate.

**Comment by cholcombe973** [comment]
This is now fixed but I'm not sure if softprops pushed it to crates.io yet.

**Comment by softprops** [comment]
I'll do that tonight

**Comment by cholcombe973** [comment]
Awesome!  Thanks

**Comment by softprops** [comment]
bumped to 0.2.0 because of the dependency changes https://crates.io/crates/goji
